require:
    - rubocop-rails
    - rubocop-rspec

AllCops:
    TargetRubyVersion: 2.7
    NewCops: enable
    Exclude:
        - 'db/**/*'
        - 'node_modules/**/*'
        - 'vendor/**/*'
        - 'bin/**/*'

Rails:
    Enabled: true
    RunRailsCops: true

Layout/LineLength:
    Max: 120

Metrics/BlockLength:
    Max: 70
    Exclude:
        - 'Rakefile'
        - 'rakelib/**/*.rake'
        - 'spec/**/*.rb'

Metrics/MethodLength:
    Max: 20

Metrics/AbcSize:
    Max: 20

Metrics/PerceivedComplexity:
    Max: 12

Metrics/CyclomaticComplexity:
    Max: 12

Layout/TrailingEmptyLines:
    EnforcedStyle: final_newline

Rails/FilePath:
    EnforcedStyle: arguments

Style/HashTransformValues:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true

Style/HashEachMethods:
    Enabled: true

